### ISSUE TITLE
remove "open folder" and "save as" requirements

### ISSUE THREAD

**Issue by Georgeouz** [Gigabyte-Giant/vscode-file-header-comment-helper#12]
Current functionality requires an opened folder (otherwise nothing happens) as well as a saved file (save-as dialog appears if necessary). It would be great if those requirements did not exist.

**Comment by Gigabyte-Giant** [comment]
Thank you for reporting this. I am aware of these issues though these aren't exactly issues...

I am currently out-of-town, but I will review this further once I return (some time after 09/18).

Once again, I appreciate the fact that you took the time to open this issue.

**Comment by Gigabyte-Giant** [comment]
In order to understand *why* these "requirements" exist, you must first understand my idea behind the extension it, as well as how I designed it to work...
I created this extension originally, because I wanted something that would **allow me to easily add file header comments** to files within my various projects.

I rarely use IDEs for any of my projects, thus I end up using tools such as Visual Studio Code-- typically, I'll just have a central folder for my project.
The name of the aforementioned folder, is also the name of the project itself.

Whenever I use Visual Studio Code to work on a project, I open the project's previously mentioned central folder.
When I want to add a file header comment, I can easily compute the name of the project, based on the name of the folder that is currently open.

In your original report, you said this:
> Current functionality requires [ ... ] *a saved file* [ ... ].

The reason a saved file is required for this extension to work is simple: 
If a file hasn't been saved yet, it doesn't necessarily exist on the disk, and **therefore doesn't have a name**.

Unfortunately, at this time, I don't believe there is anything I can do about this.

Perhaps in the future I could add prompts that ask the user for a project name, as well as a file name.
In my mind, however, that defeats the purpose of this extension entirely.

I'm going to close this, but if you have any ideas about this, please do feel-free to let me know (and reopen the issue if necessary).

**Comment by Georgeouz** [comment]
How about simply ignoring these parameters in case where a saved file and an open folder do not yet exist? The placeholders would simply not be replaced, this behaviour being backed by a hint in the documentation. Your extension would also be more universally applicable, that is either as a static or as a dynamic code snippet.

Are there other available parameters than projectName and currentFile ?
